### ISSUE TITLE
PHP syntax error on installation in some versions of PHP

### ISSUE THREAD

**Issue by benlk** [INN/news-match-popup-plugin#22]
![screen-shot-2017-10-25-at-10-21-01-am](https://user-images.githubusercontent.com/1754187/32016752-b5925104-b992-11e7-9481-4ebb19a4fefb.png)

It doesn't like the `.` in `private $settings_section = self::KEY . '_section';`

https://github.com/INN/news-match-popup-plugin/blob/0.1.2/news-match-popup-basics.php#L88-L93

For HelpScout 1410.

**Comment by rclations** [comment]
why not just use a private variable (like all the other plugin classes) instead of a constant here?

**Comment by benlk** [comment]
Because there was a fleeting possibility that other classes would use this constant to find the appropriate settings variable, but what happened instead was that we just pass the constant to those classes instead. I'll turn this into a private var.
